<a href="https://colab.research.google.com/github/Ravindrakumarnayak/Machine_learning/blob/main/recommendation_system_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np

In [52]:
movie_df=pd.read_csv("/content/Movie.csv")
movie_df

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [53]:
movie_df.head()

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [54]:
movie_df[movie_df['userId']==6]

      userId                    movie  rating
1          6         Toy Story (1995)     5.0
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [55]:
movie_df.sort_values("userId")

      userId                    movie  rating
2569       1           Jumanji (1995)     3.5
3724       2  Grumpier Old Men (1995)     4.0
0          3         Toy Story (1995)     4.0
5204       4              Heat (1995)     3.0
7444       4         GoldenEye (1995)     4.0
...      ...                      ...     ...
6463    7117              Heat (1995)     5.0
2567    7119         Toy Story (1995)     5.0
2568    7120         Toy Story (1995)     4.5
3723    7120           Jumanji (1995)     4.0
7163    7120           Sabrina (1995)     4.0

[8992 rows x 3 columns]

In [56]:
len(movie_df.userId.unique())

4081

In [57]:
movie_df.shape

(8992, 3)

In [58]:
movie_df['rating'].value_counts()

3.0    2736
4.0    2660
5.0    1394
3.5     679
2.0     542
4.5     374
2.5     277
1.0     212
1.5      61
0.5      57
Name: rating, dtype: int64

In [59]:
movie_df['userId'].value_counts()

903     10
1931    10
5881    10
156      9
1638     9
        ..
5697     1
5675     1
5664     1
5660     1
7105     1
Name: userId, Length: 4081, dtype: int64

In [60]:
len(movie_df.movie.unique())

10

In [61]:
movie_df.movie.value_counts()

Toy Story (1995)                      2569
GoldenEye (1995)                      1548
Heat (1995)                           1260
Jumanji (1995)                        1155
Sabrina (1995)                         700
Grumpier Old Men (1995)                685
Father of the Bride Part II (1995)     657
Sudden Death (1995)                    202
Waiting to Exhale (1995)               138
Tom and Huck (1995)                     78
Name: movie, dtype: int64

In [62]:
# to develop into unique structure, we use power pivot


user_movie_df=movie_df.pivot( index='userId',# rows
                             columns='movie',#columns
                              values='rating')

In [63]:
user_movie_df

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
4,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7115,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7116,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
7117,NaN,3.0,4.0,5.0,NaN,3.0,1.0,NaN,4.0,NaN
7119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
7120,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,4.5,NaN

In [64]:
user_movie_df.fillna(0, inplace=True) # fillna method will convert all NaN to O and inplace true means in the same dataframe convert it

In [65]:
user_movie_df

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
4,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7115,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7116,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7117,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7120,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [66]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [67]:
user_sim= 1- pairwise_distances(user_movie_df.values, metric='cosine')

In [68]:
user_sim # similarity matrix

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]])

In [69]:
np.fill_diagonal(user_sim,0)

In [70]:
user_sim

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 0.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 0.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 0.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        0.        ]])

In [71]:
user_sim_df=pd.DataFrame(user_sim)

In [72]:
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080
0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.390567,0.707107,0.615457,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458831,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.615457,0.000000,0.388514,...,0.800000,0.000000,0.000000,0.000000,0.989949,0.000000,0.000000,0.619422,0.000000,0.000000
4,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4076,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.658505,0.000000,0.000000,0.000000
4077,0.000000,0.000000,0.752577,0.000000,0.000000,0.489886,0.000000,0.370543,0.752577,0.657870,...,0.000000,0.752577,0.000000,0.532152,0.000000,0.658505,0.000000,0.345306,0.752577,0.468511
4078,0.000000,0.458831,0.458831,0.619422,0.000000,0.701884,0.567775,0.889532,0.458831,0.568212,...,0.344124,0.458831,0.000000,0.324443,0.648886,0.000000,0.345306,0.000000,0.458831,0.476071
4079,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,0.000000,0.622543
4080,0.553372,0.000000,0.622543,0.000000,0.553372,0.765455,0.391293,0.306519,0.622543,0.544201,...,0.000000,0.622543,0.553372,0.831497,0.000000,0.000000,0.468511,0.476071,0.622543,0.000000

In [73]:
user_sim_df.index=movie_df.userId.unique()
user_sim_df.columns=movie_df.userId.unique()

In [74]:
user_sim_df

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.390567,0.707107,0.615457,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458831,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.615457,0.000000,0.388514,...,0.800000,0.000000,0.000000,0.000000,0.989949,0.000000,0.000000,0.619422,0.000000,0.000000
11,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.658505,0.000000,0.000000,0.000000
7070,0.000000,0.000000,0.752577,0.000000,0.000000,0.489886,0.000000,0.370543,0.752577,0.657870,...,0.000000,0.752577,0.000000,0.532152,0.000000,0.658505,0.000000,0.345306,0.752577,0.468511
7080,0.000000,0.458831,0.458831,0.619422,0.000000,0.701884,0.567775,0.889532,0.458831,0.568212,...,0.344124,0.458831,0.000000,0.324443,0.648886,0.000000,0.345306,0.000000,0.458831,0.476071
7087,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,0.000000,0.622543
7105,0.553372,0.000000,0.622543,0.000000,0.553372,0.765455,0.391293,0.306519,0.622543,0.544201,...,0.000000,0.622543,0.553372,0.831497,0.000000,0.000000,0.468511,0.476071,0.622543,0.000000

In [75]:
user_sim_df.idxmax(axis=1) # idxmax gives maximum value of index will return,user id 3 and user id 11 is similar

3         11
6        168
8         16
10      4047
11         3
        ...
7044      80
7070    1808
7080     708
7087       8
7105    4110
Length: 4081, dtype: int64

In [76]:
user_sim_df.idxmax(axis=1)[0:10] # 1st 10 record

3       11
6      168
8       16
10    4047
11       3
12    6676
13    5953
14    4138
16       8
19    3603
dtype: int64

In [77]:
user_sim_df.iloc[0:5,0:5]

     3    6    8    10   11
3   0.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0
11  1.0  0.0  0.0  0.0  0.0

In [82]:
movie_df[movie_df['userId']==6]

      userId                    movie  rating
1          6         Toy Story (1995)     5.0
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [83]:
movie_df[movie_df['userId']==168]

    userId             movie  rating
60     168  Toy Story (1995)     4.5

In [ ]:
#hence we can recommend movie Sabrina to user id 6